use_frameworks!
source 'https://github.com/wangzhaoyang123/podtestspecs.git'
platform :ios, '10.0'
target 'podtest_Example' do
  pod 'podtest'

  target 'podtest_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
